<a href="https://colab.research.google.com/github/MatewosTegete/PRODIGY_DS_03/blob/main/Prodigy_DS_Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 3: Building a decision tree classifier to predict how consumers will act

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

In [ ]:
# First uploading the CSV file
bank_info = pd.read_csv("/content/drive/MyDrive/Prodigy_InfoTech/bank-additional-full.csv", delimiter=";")
# Since all the data are in a single column, let's divide it into multiple ones
with open("/content/drive/MyDrive/Prodigy_InfoTech/bank-additional-full.csv", "r") as file:
    data = []
    for line in file:
        data.append(line.strip().split(";"))  # Split and store each line's data

In [ ]:
bank_info.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
bank_info.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

Data Preprocessing

In [ ]:
# Let's first check if any data are unavailable
bank_info.isna().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [ ]:
bank_info['housing'] = bank_info['housing'].replace('admin.', 'unknown')
bank_info['housing'] = bank_info['housing'].replace('blue-collar', 'unknown')
bank_info['housing'] = bank_info['housing'].replace('self-employed', 'unknown')
bank_info['housing'] = bank_info['housing'].replace('management', 'unknown')
A = bank_info['age']
b = bank_info['housing']

# for i in range(len(b)):
#     if type(b[i]) == str:
#       b = b.replace('unknown', 'no')

modified_data = []
def replace_unwanted_values(data):

  for val in data:
    val = val.lower()
    if val not in ("yes", "no"):
      modified_data.append('no')
    else:
      modified_data.append(val)
  return modified_data
b = replace_unwanted_values(b)
df = pd.DataFrame(b)
le = LabelEncoder()
b_encoded = le.fit_transform(df)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
# For Age and Housing data to guess Housing existence based on age
# Split data into training and testing sets
A_train, A_test, b_train, b_test = train_test_split(A, b_encoded, test_size=0.2)
A_train = np.array(A_train).reshape(-1, 1)
A_test = np.array(A_test).reshape(-1, 1)
# Create and fit the decision tree model
model = DecisionTreeClassifier()

model.fit(A_train, b_train)

predictions = model.predict(A_test)

# Evaluate the model accuracy
score = accuracy_score(b_test, predictions)

print(f"Model accuracy: {score:.2f}")

Model accuracy: 0.52

So, We can say the co-relation is slightly better than random

In [ ]:
C = bank_info['job']
D = bank_info['housing']
from sklearn.preprocessing import LabelEncoder
df = pd.DataFrame(D)
le = LabelEncoder()
D_encoded = le.fit_transform(df)

encoder = LabelEncoder()

encoder.fit(bank_info['job'])

C = encoder.transform(bank_info['job'])
C = C.reshape(-1, 1)

C_train, C_test, D_train, D_test = train_test_split(A, D_encoded, test_size=0.3)

C_train = C_train.values.reshape(-1, 1)
C_test = C_test.values.reshape(-1, 1)
model = DecisionTreeClassifier()


model.fit(C_train, D_train)
predictions = model.predict(C_test)
score = accuracy_score(D_test, predictions)

print(f"Model accuracy: {score:.2f}")

Model accuracy: 0.52

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

There is also a loose connection between job and housing

In [ ]:
A = bank_info['age']
b = bank_info['marital']
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df = pd.DataFrame(b)
le = LabelEncoder()
b_encodedA = le.fit_transform(df)

encoder.fit(bank_info['age'])

A = encoder.transform(bank_info['age'])
A = A.reshape(-1, 1)

A_train, A_test, b_train, b_test = train_test_split(A, b_encodedA, test_size=0.2)

A_test = A_test.reshape(-1, 1)
model = DecisionTreeClassifier()


model.fit(A_train, b_train)
predictions = model.predict(A_test)
score = accuracy_score(b_test, predictions)

print(f"Model accuracy: {score:.2f}")

Model accuracy: 0.66

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

But our decision tree classifier guesses a much stronger connection between Age and Marital Status